import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Tn from "./tn";
// import { createClient } from "../server"

// export default async function Countries() {
//   const supabase = await createClient();
//   const { data: tn } = await supabase.from("tn").select();

//   return <pre>{JSON.stringify(tn, null, 2)}</pre>
// }

const Home: NextPage = () => {

  const [text, setText] = useState('')

  const saveData = (e) => {
    setText(e.target.value)
  }

  const handleSubmit = (e) => {
    console.log(e)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>Hello, Cyano, Welcome to Next.js on Replit!</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://docs.replit.com/category/deployments"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>After you are happy with this app, deploy it on Replit!</p>
          </a>
        </div>
      </main> */}

      <main className={styles.main}>
        <input onChange={saveData}></input>
        <button onClick={handleSubmit}>Create</button>
        <p>{text}</p>
        <Tn />
      </main>
    </div>
  );
};

export default Home;
